%Licence: GNU General Public License version 2 (GPLv2)
%load multiple GC data generated by SRI GC
function spectra = GC_dloadgc()
    [FileNamecell,PathName,Fileindex] = uigetfile({'*.asc;*.ASC', 'SRI GC ASCII'},'Select SRI GC txt files','MultiSelect', 'on');
    FileName = char(FileNamecell); % convert from cell to string list
    spectra = struct([]);
    if(Fileindex == 0)
        return;
    end
    for i=1:size(FileName,1)
        [~,name,~] = fileparts(FileName(i,:));
        filetoopen = stripstrfirstlastspaces(sprintf('%s%s',PathName,FileName(i,:)));
        fid=fopen(filetoopen);
        data = GC_SRIGCload(fid);
        fclose(fid);
        fclose all;
        if i > 1
            spectra = [spectra, struct('name',name,'spectrum',data(2), 'timecode', data(1))];
        else
            spectra = struct('name',name,'spectrum',data(2), 'timecode', data(1));
        end
    end

end
