%Licence: GNU General Public License version 2 (GPLv2)
%load multiple GC data generated by SRI GC
function spectra = GC_dloadgc()
    [FileNamecell,PathName,Fileindex] = uigetfile({'*.asc;*.ASC', 'SRI GC ASCII'},'Select SRI GC txt files','MultiSelect', 'on');
    spectra = [];
    if(Fileindex == 0)
        return;
    end
    if ~iscell(FileNamecell)
        FileNamecell = {FileNamecell};
    end
    for i=1:length(FileNamecell)
        [~,name,~] = fileparts(FileNamecell{i});
        fid=fopen(sprintf('%s%s',PathName,FileNamecell{i}));
        data = GC_SRIGCload(fid);
        fclose(fid);
        fclose all;
        spectra = [spectra, struct('name',name,'spectrum',data(2), 'timecode', data(1))];
    end
end
